// <auto-generated />
namespace Classifieds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class computers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(computers));
        
        string IMigrationMetadata.Id
        {
            get { return "201408012034196_computers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
